services:
  - type: web
    name: Organizer
    runtime: static
    buildCommand: pnpm build
    staticPublishPath: ./dist
    envVars:
      - key: VITE_SUPABASE_URL
        sync: false
      - key: VITE_SUPABASE_PUBLISHABLE_KEY
        sync: false
